### ISSUE TITLE
Should God, Seraph and Angel be renamed to Master, Hub and Tab respectively?

### ISSUE THREAD

**Issue by martinpinto** [Asynchq/jannah#1]
The names God, Seraph and Angel are confusing and do not properly describe the functionality of their respective classes. Should they be renamed to Master, Hub and Tab?

**Comment by hallvors** [comment]
(I added some readme text recently that includes god.js and seraph.js file names in instructions - would be good to rebase and fix those at the same time as this but we can do it afterwards too)
