### ISSUE TITLE
Master refactor

### ISSUE THREAD

**Issue by ronoc** [Asynchq/jannah#16]
The master at start up needs to bring a socketio server.
This is used to communicate between master and hubs. Note the hubs are where the BOAR instances are run from and therefore need monitoring.

This io channel is used for status updates that the hub needs to regularly report. The master can then use this information to determine Hub(VM) health, how busy each hub is, what country and city the hub is in.

The master exposes a RESTful API to the client (user)

- /sessions, POST
  Allows the user to request a new session
  Optionally the user should be allowed to specify the following with a JSON payload
  * Which backend to use for (phantom or slimer i.e. webkit or gecko) -> {engine: "webkit"}
  * Which location to request a tab from.
  It needs to be optional that the user can request a tab in a given location. Let's use the
  locations that Digital Ocean supports (i.e. just use the same string identifier DO uses).
  Unless we are to host our own hardware then we are dependent on our cloud providers' locations.
  It should return a JSON result which at least needs to have URL (the url:port of the created tab on the chosen hub)
https://developers.digitalocean.com/documentation/v2/#regions

- /hubs GET
Get a list of hubs registered with the master, their state, how many tabs active, max tabs, location, everything

- /health GET
Returns a JSON of the collective VM health statuses across all hubs. (what is reported via socketIO)

- /sessions GET (low priority)
Should return a list of all sessions that were created/requested within a certain time range, default 24hours. optionally - /sessions?startTime=unixtimestamp. It should store the ip address, and location of where the session request came from.
We could use http://leveldb.org/ to store the data

**Comment by martinpinto** [comment]
+1

**Comment by ronoc** [comment]
The desired layout of files for the new Jannah is here 
https://github.com/Asynchq/jannah/tree/refactor-layout

- first step is to build out the master part of Jannah, using restify and socketio and tests for each piece of API. 
- then the hub and summoner.

**Comment by dainis** [comment]
New hub should register using socket.io, otherwise it would require to maintain two lists of hubs - active(with socket.io connection) and in process of connecting(without socket.io connection)

**Comment by ronoc** [comment]
Good point. +1
