### ISSUE TITLE
Deploy first instance to Digital Ocean.

### ISSUE THREAD

**Issue by ronoc** [Asynchq/jannah#18]
Let's use Ubuntu 14.04
- [ ] simple provisioning script to install all deps for both Master and Hub 
- [ ] a new gulp task to allow for ease of deployment on either master or hub.

**Comment by miketaylr** [comment]
Note to self that I'm the blocker here. My manager is back from PTO on Wednesday so I'll know more then.

**Comment by ronoc** [comment]
Deployed to internal Mozilla vm on Friday
